// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace dbFirst.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("city")]
    [StringLength(100)]
    [Unicode(false)]
    public string City { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DepartmentName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string PhoneNo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Gender { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string BasicSalary { get; set; }
}